version: '3'

services:
  # selenium:
  #   image: selenium/standalone-chrome:latest
  #   container_name: selenium_service
  #   shm_size: 2g
  #   ports:
  #     - "4444:4444"
  #   networks:
  #     - project_net
  #   healthcheck:
  #     test: ["CMD", "curl --fail http://selenium_service:4444/wd/hub/status || exit 1"] 
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  # data_extraction:
  #   build:
  #     context: ./data_extraction
  #     dockerfile: Dockerfile
  #   ports:
  #     - "7070:7070"
  #   volumes:
  #     - ./data_extraction:/app
  #   depends_on:
  #     # selenium:
  #     #   condition: service_healthy
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - project_net

  model:
    build: 
      context: ./models
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '3'          
          memory: 512M 
    ports: 
      - "2020:2020"
    volumes:
      - ./data_extraction:/app/data_extraction
      - ./pre_processing:/app/pre_processing
    networks:
      - project_net
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - project_net
    environment:
      POSTGRES_DB: houses_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - data_house:/var/lib/postgresql/data
      - ./data_extraction/casas.csv:/casas.csv
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
networks:
  project_net:
    driver: bridge
  
volumes:
  data_house: